import Head from "next/head";
import "./globals.css";
import type { Metadata } from "next";
import Providers from "./Provider";

export const metadata: Metadata = {
  title: "To do list",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
